### ISSUE TITLE
Dependabot Configuration on GitHub actions

### ISSUE THREAD

**Issue by mfranzke** [db-ui/examples#1295]
Wouldn't this path need to include `.github`, if it's meant for GitHub Actions?

https://github.com/db-ui/examples/blame/c3e6db23a8a664f9cb965b5a00dea6ca490a5b84/.github/dependabot.yml#L4

**Comment by nmerget** [comment]
`/` is the root so we include `github` with this, see the documentation: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions
